### ISSUE TITLE
Add some mobile functionality

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/Frame-Generator#13]
Let's take a look at what needs to be added to allow sites to be 'added to home screen' (on Android) so that we have a good experience, a nice icon, and the official USGS mobile loading image: https://atthecore.usgs.gov/special-groups/visual-identity-system/mobile-applications

**Comment by mitchas** [comment]
Added shortcut icons, but I believe to get the "Add to homescreen" and open full page, we'd need to generate a second file - a manifest.json - to upload along with their index.html.

Would it be worth it? It could be an option so people could only use it if they know what it is.
